### ISSUE TITLE
How can I fully use ImmutableJS?

### ISSUE THREAD

**Issue by AsaAyers** [gaearon/redux-devtools#108]
The first time I committed to a debug session when I reloaded my state broke because `.get()` didn't exist on the objects in the store. It seemed like the solution was to provide a `stateDeserializer` to `persistState`.

```js
stateSerializer = (state) => Immutable.fromJS(state)
```

The next level problem is that `fromJS` only converts arrays to `List` or objects to `Map`. If your store relies on `Record`s, `Set`s or any of the specialized data types, it doesn't really deserialize correctly.

**Comment by FredyC** [comment]
Yeah, that's why the `stateDeserializer` there. You get the full state in pure JS and it's up to you to convert it to proper Records and other objects.

**Comment by AsaAyers** [comment]
Do you have an actual recommendation on how to solve the problem?

Obviously the state is built up through a tree of combined reducers. I could implement a custom `stateDeserializer` to do everything manually, but that approach requires `stateDeserializer` to know the details of how every reducer in my system works and I have to maintain any changes across 2 locations. That sounds like a lot of very fragile code maintained in 2 places, which is made worse by the fact that one is only for development.

**Comment by FredyC** [comment]
Yes exactly, it's somewhat fragile, but I don't know about better way for now unfortunately. I have a state deserializer like this.

    function deserializer(state) {
        if (!state) {
            return state;
        }
        return {
            ...state,
            tgDocument: Imm.List(state.tgDocument.map((row) => new TGRow(row))),
            tgFocus: new TGZoom(state.tgZoom),
        };
    }

**Comment by gaearon** [comment]
Closing as inactive.

**Comment by AsaAyers** [comment]
For anyone who finds this in the future: My solution was to give up on Immutable JS and use https://github.com/leoasis/redux-immutable-state-invariant to tell me if I mutate state somewhere.

As long as you turn on `es7.objectRestSpread` it's easier to work with than Immutable and you just have to remember to be intentional about not mutating state.

**Comment by kachkaev** [comment]
I'm playing with [the boilerplate](https://github.com/mxstbr/react-boilerplate) by @mxstbr, which uses Immutable.js for the entire state and I can't figure out how `persistState` enhancer should look like in the devtools. Because an node that is being created when I open `?debug_session=42` has a dynamic name, Immutable's `combinedReducer` fails saying:
```
The previous state received by the reducer is of unexpected type.
Expected argument to be an instance of Immutable.Iterable with
the following properties: "a", "b", "c", "d".
```
And it looks like I can't supplement the root reducer with some extra dummy reducer in `combineReducers` from `redux-immutable` myself as the name is unpredictable.

I was getting myself familiar with redux-devtools via [Walkthrough.md](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md) so thought that it would be good to mention the case of an Immutable store there. I've seen some threads in various repos that are trying to approach the issue I face, but it would be probably good to have some hint where there's the highest number of newcomers. @gaearon could you please add a couple of lines of text describing what to use instead of `redux-devtools/persistState` you your state is Immutable?
