### ISSUE TITLE
Use Immutable

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools#161]
It's not something to do in 3.0, but in the future we should use Immutable internally for better memory usage and performance. This will be a breaking change for monitors, so this can be something we can do for 4.0 given enough interest in better perf.

**Comment by rileylark** [comment]
FYI @gaearon our internal redux-ish system uses Immutable and we have found it to be pretty cumbersome to use. I imagine it does save you from cloning bunches of times, but we have actually just been deciding to ditch ImmutableJS and follow your lead into POJO territory. Do you have performance improvement estimates?

We also use flow to type our reducers and of course Immutable.Map et al can't type `state.setIn(['gl', 'typing', 'this'], ...)`, which has been another big reason we've been thinking of switching to your POJO approach. It's not so bad to typecast at the end of `getState()` but it would be nice to get autocomplete etc inside our reducers as well as outside.

Finally, we find ourselves calling `toJs()` on our Immutable state _anyway_, so that our views don't have to call `state.getIn(['counters', 2, 'count'])` - and any external libraries of course expect plain objects too. I assume `toJs()` is just about as expensive as cloning your state (it must clone your state right?).

And _really_ finally, we have a few times accidentally put mutable objects into our Immutable store, which makes it... a mutable store anyway!

So all this is to say that we started out assuming Immutable would be best for everything - development, performance, clarity - and actually have so far experienced the opposite.

**Comment by gaearon** [comment]
Fair enough. Yes, `toJS()` negates the benefits on Immutable. In this case, I don't know yet—maybe it will make perf better, or maybe not. Regardless, with recent optimizations in `next` branch it may not be needed at all.
