### ISSUE TITLE
findDOMNode - use on react-dom instead of react

### ISSUE THREAD

**Issue by ondrejbartas** [gaearon/redux-devtools#164]
React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

**Comment by ondrejbartas** [comment]
#165

**Comment by gaearon** [comment]
From README:

<img width="577" alt="screen shot 2015-10-21 at 16 28 16" src="https://cloud.githubusercontent.com/assets/810438/10637901/c36a41da-7810-11e5-82cc-b2f8eb5722e4.png">

Also, using search will give you:

<img width="856" alt="screen shot 2015-10-21 at 16 28 54" src="https://cloud.githubusercontent.com/assets/810438/10637917/de2f1496-7810-11e5-9630-87de0892ed47.png">

The warnings are gone in [3.0 beta](https://github.com/gaearon/redux-devtools/releases/tag/v3.0.0-beta-2). Please use it. We will not fix them in 2.0 because it's a breaking change anyway.
