### ISSUE TITLE
Toggle visibility isn't working on Firefox

### ISSUE THREAD

**Issue by Ghostavio** [gaearon/redux-devtools#182]
Tested both on OSX and Ubuntu, Ctrl+H has no effect whatsoever on Firefox, but it works just fine on Chrome and Opera.

**Comment by gaearon** [comment]
What version are you using?

**Comment by marcenuc** [comment]
Same problem for me with Firefox Developer Edition 44.0a2 (2015-11-11) on Ubuntu 15.10 (wily).

**Comment by marcenuc** [comment]
I have a workaround, but no time for a PR now. Then I post here the workaround for now.

The problem is in `redux-devtools-dock-monitor`.  Applying the following patch to `./node_modules/redux-devtools-dock-monitor/lib/DockMonitor.js`, it works.

    $ diff -u /tmp/DockMonitor-orig.js ./node_modules/redux-devtools-dock-monitor/lib/DockMonitor.js
    --- /tmp/DockMonitor-orig.js	2015-11-12 10:11:03.888556412 +0100
    +++ ./node_modules/redux-devtools-dock-monitor/lib/DockMonitor.js	2015-11-12 10:11:22.816315455 +0100
    @@ -88,7 +88,7 @@
         }
         e.preventDefault();
     
    -    var key = event.keyCode || event.which;
    +    var key = e.keyCode || e.which;
         var char = String.fromCharCode(key);
         switch (char.toUpperCase()) {
           case this.props.toggleVisibilityKey.toUpperCase():
    
I think the problem is in the compilation of the file because I do not see the error (wrong variable name) in the original sources and I do not know why it works in Chromium.

**Comment by marcenuc** [comment]
This bug is fixed by https://github.com/gaearon/redux-devtools-dock-monitor/commit/ecc67af0e3f973d0bd915453253e6b1f88c1407c

**Comment by SkateFreak** [comment]
toggling not working on Firefox 42.0 on OSX El-Capitan 10.11.1

**Comment by MoOx** [comment]
Not working in Firefox 45a on OSX El-Capitan 10.11.1

**Comment by gaearon** [comment]
The fix was not released as a package update yet.

**Comment by Ghostavio** [comment]
so, as the bug is fixed but not released yet, I'll close the issue again

**Comment by gaearon** [comment]
Fixed in 3.0.
