### ISSUE TITLE
multiple persist stores

### ISSUE THREAD

**Issue by Raffiki** [gaearon/redux-devtools#183]
Is there any interest in supporting multiple persist store (besides localstorage)?

I would use it to persist a session's state and do post mortem debugging on it. Not sure if this is the right place for such a thing though.

**Comment by gaearon** [comment]
We don't plan to support this here, but please feel free to copy `persistState()` and create a separate module based on it, and then post a link to it for other folks. :-)

**Comment by jxm262** [comment]
@Raffiki  sorry to chat in this thread, but was wondering if you'd like to chat about this?  I'm working on something similar (will put in a separate module) and I'd like to bounce some ideas.

**Comment by jxm262** [comment]
@Raffiki  @gaearon  Again, my apologies for chatting back in a closed ticket.  I moved the logic of `persistState` into a separate module (not yet published) - https://github.com/jxm262/redux-devtools-state-store/tree/master   

I'd like some ideas on how this could be implemented to a use other storage mechanisms.  Would this be a possible solution - 
1. Change the module to have the user pass in a backing storage and then implement a generic `get()`, `set()`, and `remove()` functionality, instead of using localstorage?

example pseudocode - 
```
//implementation file
import persistState from 'redux-devtools-state-store'
import myCustomPersistence from 'my-persistence'   //could be connected to a db, json file, etc..

const enhancer = compose(
  applyMiddleware(thunk),
  DevTools.instrument(),
  persistState(myCustomPersistence)
);


//persistState functionality (change to current persistState code)
return next => (reducer, initialState, enhancer) => {
   ...
    const json = passedInStorage.getItem(key);
    ...
    passedInStorage.removeItem(key);
    ...
    passedInStorage.setItem(key, getState());
}
```

Any ideas?

**Comment by jxm262** [comment]
Ok , just updated my repo with a bit more.  Feel free to take a look and give any feedback.  I think this could be useful

https://github.com/jxm262/redux-devtools-state-store

**Comment by Raffiki** [comment]
Want to try this out with indexeddb https://github.com/mozilla/localForage

**Comment by jxm262** [comment]
@raffiki  if you don't get to it first, ill take a look tomorrow.  Im myself working on a system to save all of this data to an external db during my qa process. So I can share a replayable history whenever a test fails. 

Feel free to msg me sometime. Would like to collab on some ideas :)
