### ISSUE TITLE
DevTool Component positioned relative with dragging

### ISSUE THREAD

**Issue by yepnamesjames** [gaearon/redux-devtools#226]
Are there any opinions about the DevTool component adjusting as a sidebar similar to Chrome's dev tool? I have noticed the overlay has gotten in my way a bit. I would be down to try and pull it off, but wanna check if there strong opposition for it in this repo.

**Comment by ElegantScripting** [comment]
No opposition, give it a shot! That's what open source is for.

I get the same issue sometimes. If I may, I would suggest adding multiple small layout icons positioned absolute on the bottom of the component, like so:

1. Fix to left side of screen
2. Fix to right side of screen
3. Enable moving around screen by dragging

Something else I'm thinking of: ***what if instead of the DevTools component sitting on top of the UI, it readjusted the width of the ui, and crammed itself in the remaining space?*** Assuming the user-interface is responsive or your screen is large enough, it should still give you plenty of room to work with while still enabling you to work with no hassle in development.

**Comment by gaearon** [comment]
Feel free to do it!

The actual layout logic is not in this repo—you're probably using [`DockMonitor`](https://github.com/gaearon/redux-devtools-dock-monitor). Feel free to write a `SidebarMonitor` that works in the way you want.

Closing as non-actionable in this repo.
