### ISSUE TITLE
Dispatch multiple actions 

### ISSUE THREAD

**Issue by timarney** [gaearon/redux-devtools#309]
I'm looking into how hard it would be to capture actions in production when there's an error for replaying later in dev.

Ideally with the ability to pass in multiple actions and run them something like this

![screen shot 2016-08-12 at 1 38 27 pm](https://cloud.githubusercontent.com/assets/62242/17631446/1ade2002-6092-11e6-80d6-4b3b69167b0c.png)

It seems like if I could paste in an array of actions to run it would be easier to log in production than trying to mimic the export from the dev tools.

I initially was wondering about trying to get the store export much like when clicking the dev tools export and saving that 
see - http://stackoverflow.com/questions/38922861/export-log-to-error-tracking-service 

but there's quite a few extra keys that seem to be required computedStates, stagedActionIds etc... 

If pasting in multiple actions for dispatch isn't an option what's the minimal json format needed to do an import i.e. would I need to calculate stagedActionIds etc...   

Here's a repo with a basic concept of what I'm doing - https://github.com/timarney/redux-trackjs-logger

**Comment by zalmoxisus** [comment]
Importing an array of actions from file should work now (as discussed in https://github.com/zalmoxisus/redux-devtools-extension/issues/173).

> If pasting in multiple actions for dispatch isn't an option what's the minimal json format needed to do an import i.e. would I need to calculate stagedActionIds etc...

Your array above should work just fine. Though we accept importing in such format, the reason why we don't export in this format is because we don't store all the actions from the beginning, which would be a too large object. Another reason is that having the states allow you to postprocess the data statically for analytics or generating tests.

There would be an out of the box solution, as I promised in [my React Europe talk](https://youtu.be/cbXLohVbzNI?t=1122). I will come with more details a bit later.

Dispatching an array of actions would be useful indeed, but not for importing them, as usually we have some actions which run in the background when the app starts, and they would be duplicated.

**Comment by timarney** [comment]
Cool thanks for the information.  

That's this commit correct? https://github.com/zalmoxisus/redux-devtools-instrument/commit/8416bf714b9804a9519629de14f7cc29a62fb9be 

Do these updates land in the Chrome Dev Tools extension automatically (auto update)?   Or does that need to be setup per https://github.com/zalmoxisus/redux-devtools-instrument

**Comment by zalmoxisus** [comment]
Yes, Chrome autoupdates the extension. Those changes should be there.

**Comment by timarney** [comment]
Perfect I'll follow up on the other thread if I run into issues.
