### ISSUE TITLE
Why does this require a peer dependency of react-redux?

### ISSUE THREAD

**Issue by jrajav** [gaearon/redux-devtools#337]
After one of the recent updates, I now get this error for every npm operation:

```
`-- UNMET PEER DEPENDENCY react-redux@^4.0.0 || ^5.0.0  

npm WARN redux-devtools@3.3.2 requires a peer of react-redux@^4.0.0 || ^5.0.0 but none was installed.
```

Why is react-redux required? I am using react and redux only and not react-redux and yet redux-devtools seems to work fine.

**Comment by zalmoxisus** [comment]
It is necessary to [connect monitors](https://github.com/gaearon/redux-devtools/blob/master/src/createDevTools.js), which are React components. I don't think using it without any monitors makes sense, but if it does then use [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument) instead.

You can use [browser extension](https://github.com/zalmoxisus/redux-devtools-extension), which doesn't require to have any dependencies, because everything is decoupled from your app.

**Comment by jrajav** [comment]
Ah! I wasn't aware the package wasn't necessary when you have the browser extension. Sorry to waste your time-- thank you!
