### ISSUE TITLE
UI performance is too slow when DevTools is enabled

### ISSUE THREAD

**Issue by iamyardem** [gaearon/redux-devtools#347]
Hello. I found out that my UI is getting slow when LogMonitor contains many actions in history. The more actions in the history, the slower UI responsiveness. I can accelerate performance simply committing all actions. I am using redux-form which dispatches many actions on each input key press. But despite that amount of actions dispatched by redux-form, the UI works fast in production mode (when I don't include DevTools at all). Is there any chance I am using DevTools in a wrong way? Or is there any option to display just let say last 10 dispatched actions? 

Here is the list of packages I am using that might be related to this issue:

dependencies:
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-redux": "^4.4.5",
    "react-router": "^3.0.0",
    "react-router-redux": "^4.0.6",
    "redux": "^3.6.0",
    "redux-form": "^6.2.1",
    "redux-saga": "^0.12.1"

 devDependencies:
    "react-hot-loader": "^3.0.0-beta.6",
    "redux-devtools": "^3.3.1",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.0.11",
    "webpack": "^2.2.0"

**Comment by zalmoxisus** [comment]
Yes, you can set `maxAge` to `10`. See [the docs](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#use-devtoolsinstrument-store-enhancer) and [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument#api) for more details.

The reason why monitors components are slow is that React is in dev mode. [Redux Extension](https://github.com/zalmoxisus/redux-devtools-extension) has it in production mode, also batches multiple dispatched actions together in order to not get the UI flooded. If you'll give it a try (it's just [one line to change](https://github.com/zalmoxisus/redux-devtools-extension#1-with-redux)), I'd be curious to know whether the perf is better or not for your use case.

**Comment by iamyardem** [comment]
Thanks, @zalmoxisus. The extension works without any problem. Cheers 👍

**Comment by liesislukas** [comment]
I had the same issue. I have hot-reload of components and some bits of state are fetched on continuous updates and in the end I have UI with tens of thousands of DOM elements in DevTools and lag. This fixed it:

      DevTools.instrument({maxAge: 15}),
