### ISSUE TITLE
toggleAction

### ISSUE THREAD

**Issue by cptroot** [gaearon/redux-devtools#6]
I wanted to ask, what's the reason that you decided to make clicking an action toggle the action, rather than rewind time to that action as it was when you first demoed the early version of the devtools. It seems like this version is more fragile.

For example, if we look at the counter example from this repository. If we first take the following sequence of actions:

Increment, Increment, Decrement, Increment if Odd, Increment if Odd, Increment
(Increment, Increment, Decrement, Increment,               , Increment)

We end up at 3. If we now toggle the second increment action, we end up at 
(Increment, ~~Increment~~, Decrement, Increment,            , Increment)

This gives us a total of 2. However, if we try and replay the sequence of actions, we would get

Increment, ~~Increment~~, Decrement, Increment if Odd, Increment if Odd, Increment
(Increment, ~~Increment~~, Decrement,                    ,                      , Increment)

Giving us 1.

This desync doesn't occur if we simply rewind time to any point, because we can't obtain an invalid history by going to a previous point in time.

Could we get back the functionality from the first demo, where toggling rewound time?

**Comment by gaearon** [comment]
>I wanted to ask, what's the reason that you decided to make clicking an action toggle the action, rather than rewind time to that action as it was when you first demoed the early version of the devtools. 

Actually when demoing I had a super secret shortcut where shift+click would work as “toggle all actions before” (or after, depending on where you do it) and just click worked as “toggle action”.

I removed it because it was done in a hacky way, and I think toggling and jumping require different UIs. (See also https://github.com/gaearon/redux-devtools/pull/5).

I think there is a misunderstanding here: `Increment if Odd` will actually never get into the action history. Only the “raw” actions get into the history so they can never “disappear” later because some condition has changed. The total count of actions is always the same. Only the ones you toggled explicitly will be skipped.

I find toggling immensely useful for debugging. You can filter out actions unrelated to the scenario you're working on. Moreover, you can quickly check different action orders just by toggling them and seeing whether a crash occurs (which will be displayed).

That said, I totally understand the the toggling UI doesn't make sense for debugging some kinds of applications or problems (e.g. debugging animation). This is why you can use `JUMP_TO_STATE` added in #5 to implement an alternative monitor that lets you just go back and forward, whether with a slider or an action log.

Does this help?

**Comment by erikras** [comment]
I foresee a UI with several buttons by each action, e.g. rollback (jump?) to here, make this action never have happened (toggle?), etc. Eventually the filtering demoed at ReactEurope will be available as a text box in the devtools sidebar. All easy stuff not worthy of @gaearon's time.

**Comment by gaearon** [comment]
Closing as inactive. Let's track the "powerful UI" in #74.
