### ISSUE TITLE
Export as a unit test

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools#8]
I really want to see a custom monitor (#3) that lets you record a session and then export it as a unit test where each intermediate state + action => state combination is written as an assertion.

**Comment by lapanoid** [comment]
Here you go - https://github.com/lapanoid/redux-devtools-gentest-plugin

**Comment by dozoisch** [comment]
@lapanoid this looks awesome

**Comment by lapanoid** [comment]
@dozoisch thanks!

**Comment by lapanoid** [comment]
I copied ui from @gaearon extensively because I am not a designer and I wanted to make this plugin fast. So there are a lot of ui problems, it is not really responsitive for example. I guess we need a design guy to fix it. At least there should be some interface to manage different plugins, for now I just use left panel and it is really space consuming but even if I make it smaller we still need some common way to build plugins and special place for them in terms of ui.

**Comment by gaearon** [comment]
Closing as solved in userland.
We might get back to this after integrating a better monitor composition solution in #132.
